### ISSUE TITLE
"source" files under a folder for Python modules

### ISSUE THREAD

**Issue by gaow** [cumc/dsc#1]
Test example

[issue_1.tar.gz](https://github.com/cumc/dsc/files/5302525/issue_1.tar.gz)

to run it:

```
dsc test.dsc
```
I get error message:

```
[.ERROR: module test (id=6762aa22df05ae81) returns an error.
] Failed with 2 steps processed (2 jobs completed)
ERROR: [7ab153bb-2938-4958-8cae-2c6d4eb7607f]: [test]: [0]: 
Failed to execute python3 .sos/test_0_c98bb79d.py
exitcode=1, workdir=/home/gw/tmp/29-Sep-2020, stderr=test/test/test_2.stderr
---------------------------------------------------------------------------
[DSC]: Exits with 1 pending step (output validation)
```

And if I run 

```
python .sos/test_0_c98bb79d.py
```

it reads:

```
Traceback (most recent call last):
  File ".sos/test_0_c98bb79d.py", line 22, in <module>
    res = foo()
  File ".sos/test_0_c98bb79d.py", line 20, in foo
    print_me()
NameError: name 'print_me' is not defined
```

Now, looking into `.sos/test_0_c98bb79d.py`, you see the line that supposedly load the `print_me` function, from `lib/lib.py`, is 

```
__source_dirs__(['lib'])
```

which comes from [this function](https://github.com/cumc/dsc/blob/650110e54082e1fe27e726f3db218c5f3ef8ef13/src/dsc_io.py#L273).

First, it is an ugly hack in many ways. It wants to mimic the behavior of R and bash's `source` function that for specified files it can `source` all functions inside it to the global name space. In Python it is not easy to achieve. I can only come up to so far as the `source_dirs` function above, which works perfectly if the function itself is not loaded from `dsc.dsc_io`. For example if I have the file `lib.py` (inside the test data-set) under my current directory, then it works flawlessly:

```python
$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def source_dirs(dirs):
...     import sys, os, glob
...     reserved = ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']
...     for item in dirs:
...         item = os.path.abspath(os.path.expanduser(item))
...         sys.path.append(item)
...         for module in glob.glob(f'{item}/*.py'):
...             m = __import__(os.path.basename(module)[:-3])
...             for i in dir(m):
...                 if not i in reserved:
...                     globals()[i] = getattr(m,i)
... 
>>> source_dirs(['lib'])
>>> print_me()
9
>>> exit()

```

Now we need to try make it happen in DSC ...

**Comment by gaow** [comment]
@junyanj1 @lmxy0212 the ticket above is relevant in several ways: 

1. it involves many components that, overall, is a good demonstration how DSC works under the hood
2. it reflects some of the poor decision making and engineering on my end :) 
3. it is a "feature" that needs to be implemented

Hopefully one of you can take a look and help with a fix!

**Comment by gaow** [comment]
Thanks @junyanj1  for the patch #2 . Next time when you commit a patch you can write in the commit message something like `"Implement ... , #1"` to highlight it is for issue `#1`, so the commit will show in this ticket. 

It definitely will work, although not very elegant. In fact my `source_dir`, with the `reserved` list, and everything else, is not elegant -- compared to R's `source` function. But I guess this is something Python does not want us to do, so it cannot be more elegant?

**Comment by gaow** [comment]
Let's use this solution from @junyanj1 for now until problem emerges from it.
